### ISSUE TITLE
args

### ISSUE THREAD

**Issue by sec13b** [overheavenlyshadows/massnmap#1]
sudo masscan -iL file.txt <masscan args> --nm <nmap args>

can you add a example , no offense ,i just want learn

**Comment by overheavenlyshadows** [comment]
Sure mate. Two ways of my usual use:

Single target host:
`sudo massnmap 192.168.1.1 -p- --rate 4000 --nm -Pn -T4 -A --script=vulners
`
Multiple target hosts:
`sudo massnmap 192.168.1.1 -iL file.txt --rate 4000 --nm -Pn -T4 -A --script=vulners
`
File should contains IPs line by line. Here is example:

> 192.168.1.1
> 192.168.1.2
> ...
> 192.168.255.255

All args before "--nm" arg ("-p-", "--rate 4000") are massnmap's args. Everything after "--nm" is nmap's args.

**Comment by sec13b** [comment]
sudo massnmap 192.168.1.1 -iL file.txt --rate 4000 --nm -Pn -T4 -A --script=vulners 

192.168.1.1 is the local ip (kali ip)

and in file.txt class which want to scan 
192.168.1.1
192.168.1.2
...
192.168.255.255

**Comment by overheavenlyshadows** [comment]
Sorry, i made i typo during copypaste. 

Use should use only single IP or flag -iL with filename. So to scan your home subnet you can use any of following ways:

1. Scanning by CIDR:
`sudo massnmap 192.168.1.0/24 --rate 4000 --nm -Pn -T4 -A --script=vulners`

2. Scanning by using `-iL `option and file.txt with IPs:

`sudo massnmap -iL file.txt --rate 4000 --nm -Pn -T4 -A --script=vulners`

if you want scan single host use:
`sudo massnmap 192.168.1.1 --rate 4000 --nm -Pn -T4 -A --script=vulners`

**Comment by sec13b** [comment]
last question , what is the best rate to scan . for small range to scan every ip from 192.168.1.2 to 192.168.5.255
to get

**Comment by overheavenlyshadows** [comment]
Unfortunately, i should answer: "Depends on"
It depends on routing traffic hardware, it's about OS which handles requests. But usually 4000 is ok. The lowest thing i used was 2500. But sometimes i use 16000. Just test on your own :)

**Comment by sec13b** [comment]
OK , thank you a lot.

**Comment by sec13b** [comment]
python3 massnmap.py -iL a.txt --rate 4000 --nm -Pn -T4 -A --script=vulners

===============
Massnmap v1.1.1
===============

[INFO] Checking if args are correct...

[ERROR] Unknown error:
wait 0: empty parameter
FAIL: no ports were specified
 [hint] try something like "-p80,8000-9000"
 [hint] try something like "--ports 0-65535"

**Comment by overheavenlyshadows** [comment]
there is a hint
```
[hint] try something like "-p80,8000-9000"
[hint] try something like "--ports 0-65535"
```
if you want scan all ports use following command:
`python3 massnmap.py -iL a.txt -p- --rate 4000 --nm -Pn -T4 -A --script=vulners`

**Comment by sec13b** [comment]
you are good teacher
